# In-Class Programming Activity, Day 6

# Ilse Dippenaar
```{r, echo=FALSE}
library(ggplot2)
library(mosaicData)
```


## Task 1
```{r}
myHistogram <- function(X, nbins, fill="seagreen4", ...) {
  evenly_spaced <- seq(min(X), max(X), length.out = nbins+1)
  bin_counts <- table(cut(X, evenly_spaced))
  hist_basics <- data.frame(xL = evenly_spaced[1:nbins],
                          xR = evenly_spaced[2:(nbins+1)],
                          count = as.numeric(bin_counts))
  make_one_bar <- function(point) {
    xLeft <- point$xL
    xRight <- point$xR
    height <- point$count
    res <- data.frame(
                x = c(xLeft,  xLeft,  xRight, xRight, NA),
                y = c(    0, height,  height,      0, NA)
    )
    res
  }
  # ================
  one_to_five <- function(hist_data) {
    bars <- NULL
    for (k in 1:nrow(hist_data)) {
      new_bar <- make_one_bar(hist_data[k, ])
      bars <- rbind(bars, new_bar)
    }
    bars
  }

  My_bars <- one_to_five(hist_basics)
  plot(My_bars, type="n", ...)
  polygon(My_bars, col = fill)
  
  sortedX <- sort(X)
  scale <- hist_basics[["count"]] %*% diff(evenly_spaced)
  lines(sortedX, dnorm(sortedX, mean(X), sd(X))*scale, col = "red", lwd=1.5)
}
with(Galton, myHistogram(height, 10))
```

## Task 2
```{r}
v <- rnorm(10, mean=100, sd=1)
bw <- diff(range(v))/sqrt(length(v))
kernel <- function(v, x) dnorm(v, x, bw)
x <- sort(runif(100, min(v)-2*bw, max(v)+2*bw))
Dvals <- outer(v, x, kernel)
density <- colSums(Dvals)/length(v)
density_df <- data.frame(x = x, density = density)
ggplot(density_df, aes(x, density)) + geom_line()
```

## Task 3
```{r}
plotdensity <- function(v, xlim = NA) {
  bw <- diff(range(v))/sqrt(length(v))
  kernel <- function(v, x) dnorm(v, x, bw)
  x <- sort(runif(100, min(v)-3*bw, max(v)+3*bw))
  Dvals <- outer(v, x, kernel)
  density <- colSums(Dvals)/length(v)
  density_df <- data.frame(x = x, density = density)
  p <- ggplot(density_df, aes(x, density)) + geom_line()
  if (!is.na(xlim)) p <- p + xlim(xlim)
  show(p)
  invisible(density_df)
}
plotdensity(v)
```


## Test statements

```{r}
scoreActivity::score253(6)
```