# In-Class Programming Activity, Day 8

## Ilse Dippenaar

### Task 1
```{r}
x <- runif(100, 20, 70)
My_data <- data.frame(x=x, y=5+3*x+2*rnorm(100))
with(My_data, plot(x, y, pch=20))
LL_line <- function(params) with(My_data, sum(log(dnorm(y-(params[1]*x+params[2]), sd = params[3]))))
testA <- LL_line(c(3, 5, 2))
testB <- LL_line(c(4, 1, 10))
starting_params <- c(4, 1, 10)
best <- optim(starting_params, LL_line, control=list(fnscale = -1))
```

### Task 2
```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))
taxi_likelihood <- function(pars) with(Taxi_trips, sum(log(
  dexp(fare_amount-(pars['base_fare'] + pars['per_mile']*trip_distance),
       pars['params'])+1e-100)))
starting_params <- c(base_fare = 2.00, per_mile = 4.00, params = 1/3)
best <- optim(starting_params, taxi_likelihood, control = list(fnscale = -1))
with(Taxi_trips, plot(trip_distance, fare_amount, pch=20))
abline(best$par['base_fare'], best$par['per_mile'], col='red', lwd=2)
```

## Test statements

```{r}
scoreActivity::score253(8)
```