# In-Class Programming Activity, Day 9

## Ilse Dippenaar

```{r}
poker_deck <- c(outer((10 * 2:14), 1:4, '+'))
suits <- function(cards) cards %% 10
ranks <- function(cards) cards %/% 10

is_straight <- function(hand) max(diff(sort(ranks(hand)))) == 1
is_flush <- function(hand) max(table(suits(hand))) == 5
is_straight_flush <- function(hand) is_straight(hand) && is_flush(hand)
is_royal_flush <- function(hand) is_straight_flush(hand) && max(ranks(hand)) == 14
is_four_of_a_kind <- function(hand) max(table(ranks(hand))) == 4
is_three_of_a_kind <- function(hand) max(table(ranks(hand))) == 3 && length(table(ranks(hand))) != 2
is_two_pair <- function(hand) sum(table(ranks(hand)) == 2) == 2
is_pair <- function(hand) length(table(ranks(hand))) == 4
is_full_house <- function(hand) max(table(ranks(hand))) == 3 && length(table(ranks(hand))) == 2
```

```{r}
funcs <- list(is_royal_flush, is_straight_flush, is_four_of_a_kind, is_full_house, is_flush, is_straight, is_three_of_a_kind, is_two_pair, is_pair)
  names <- c("Royal Flush", "Straight Flush", "Four of a Kind", "Full House", "Flush", "Straight", "Three of a Kind", "Two Pair", "One Pair")
before_draw <- function(hand=hand) {
  if (missing(hand)) hand <- sample(poker_deck, 5)
  for (i in 1:length(funcs)) {
    if (funcs[[i]](hand)) return(c(name=names[i], num=i))
  }
  return(c(name="None", num=length(names)+1))
}
table(sapply(1:1000, FUN=function(...) before_draw()['name']))
```
```{r}
texas_hold_em <- function(hand) {
  labeled <- apply(combn(hand, 5), 2, 
                   function(hand) list(hand=hand, num=before_draw(hand)['num']))
  labeled[order(unlist(lapply(labeled, function(x) x$num)))][1][[1]]$hand
}
texas_hold_em(sample(poker_deck, 7))
```


## Test statements

```{r}
scoreActivity::score253(9)
```